name: i_am_rich
description: A simple app with a diamond image


version: 1.0.0+1

environment:
  sdk:

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/


